title: Align Main Camera to Scene view
hero_image: images/banner.png
description: Align Main Camera to Scene view
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Align Main Camera to Scene view
